version: 2.1
jobs:
  run_tests:
    docker:
      - image: tiangolo/uwsgi-nginx:python3.8
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            pip install --user -r flask/requirements.txt
      - run:
          name: Run Unit Tests
          command: |
            python -m pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained.html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
workflows:
  build_test:
    jobs:
      - run_tests
