version: 2.1


jobs:
  run_tests:
    docker:
      - image: tiangolo/uwsgi-nginx:python3.8
    steps:
      - checkout
    run:
      name: Install Python Dependencies
      command: |
        echo 'export PATH=>$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
        pip install --user -r requirements.txt
    run:
      name: Run Unit Tests




workflows:
  main:
    jobs:
      - run_tests
